apiVersion: v2
appVersion: 0.3
name: kube-review-prune
description: Helm chart that deploys a kube-review prune job
keywords:
  - review
  - environment
  - prune
maintainers:
  - name: FindHotel
type: application
sources:
- https://github.com/FindHotel/kube-review
version: 0.3
