apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: "1"
            memory: 2048Mi
          requests:
            cpu: "2"
            memory: 1024Mi
