apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: keda
spec:
  host: "PLACEHOLDER"
  scaleTargetRef:
    deployment: kube-review-deployment
    service: kube-review-service
    port: 80
  replicas:
    min: 0
    max: 2
