kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: xkcd
spec:
    hosts:
        - "PLACEHOLDER"
    pathPrefixes:
        - /test
    scaleTargetRef:
        name: kube-review-deployment
        kind: Deployment
        apiVersion: apps/v1
        service: kube-review-service
        port: 80
    replicas:
        min: 0
        max: 1
