kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: keda-http
spec:
    hosts:
        - "PLACEHOLDER"
    pathPrefixes:
        - /test
    scaleTargetRef:
        name: kube-review-deployment
        kind: Deployment
        apiVersion: apps/v1
        service: kube-review-service
        port: 80
    replicas:
        min: 0
        max: 1
    scalingMetric:
        requestRate:
            granularity: 1s
            targetValue: 100
            window: 1m
