apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: keda-http
spec:
  host: "PLACEHOLDER"
  targetPendingRequests: 100
  scaleTargetRef:
    deployment: kube-review-deployment
    service: kube-review-service
    port: 80
  cooldownPeriod: 900
  replicas:
    min: 0
    max: 1
