apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kube-review-
commonLabels:
  app.kubernetes.io/name: kube-review
resources:
  - namespace.yml
  - serviceaccount.yml
  - service.yml
  - deployment.yml
  - vpa.yml

secretGenerator:
- name: secret
  envs:
  - secrets.txt
  type: Opaque
  options:
    disableNameSuffixHash: true

patches:
  - path: patches/service.patch.json
    target:
      kind: Service
  - path: patches/deployment.patch.json
    target:
      kind: Deployment
  - path: patches/namespace.patch.json
    target:
      kind: Namespace
