apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: deployment
  resourcePolicy:
    containerPolicies:
      - containerName: 'kube-review'
        minAllowed:
          cpu: "1"
          memory: 600Mii
        maxAllowed:
          cpu: 1
          memory: 600Mi
        controlledResources: ["cpu", "memory"]
