#!/bin/sh

DATE=$(date -u +'%Y-%m-%dT%H:%M')

echo "Generating the Certificate"
AWS_ACCESS_KEY_ID=$LETSENCRYPT_AWS_ACCESS_KEY_ID \
AWS_SECRET_ACCESS_KEY=$LETSENCRYPT_AWS_SECRET_ACCESS_KEY \
certbot certonly \
--dns-route53 \
--dns-route53-propagation-seconds 30 \
--email $EMAIL \
--server $SERVER \
-d $DOMAIN

echo "Copying of the Certificate to S3"
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
aws s3 sync /etc/letsencrypt/{csr,keys} s3://$BUCKET_S3/$DATE/

echo "Exporting the csr.pem and key.pem"
export CSR=$(cat /etc/letsencrypt/csr/0000_csr-certbot.pem | base64 | tr -d \\n)
export KEY=$(cat /etc/letsencrypt/keys/0000_key-certbot.pem | base64 | tr -d \\n)

echo "Updating the Certificate on the Kubernetes Cluster"
kubectl config use-context $KUBE_CONTEXT
cat <<EOF | envsubst | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: $SECRET_NAME
  namespace: $NAMESPACE
data:
  tls.crt: $CSR
  tls.key: $KEY
type: kubernetes.io/tls
EOF
