#!/bin/sh

DATE=$(date -u +'%Y-%m-%dT%H:%M')

echo "INFO - Generating the Certificate..."
certbot certonly \
--dns-route53 \
--dns-route53-propagation-seconds 30 \
--email $EMAIL \
--server $SERVER \
--non-interactive \
--agree-tos \
-d $DOMAIN

echo "INFO - Copying of the Certificate to S3..."
aws s3 sync /etc/letsencrypt/ s3://$BUCKET_S3/$DATE/

echo "INFO - Getting the CSR and KEY file..."
CRT=$(cat /etc/letsencrypt/live/"${DOMAIN:2}"/fullchain.pem | base64 | tr -d \\n)
KEY=$(cat /etc/letsencrypt/live/"${DOMAIN:2}"/privkey.pem | base64 | tr -d \\n)

echo "INFO - Updating the Certificate on the Kubernetes Cluster..."
kubectl config use-context $KUBE_CONTEXT
cat <<EOF | envsubst | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: $SECRET_NAME
  namespace: $NAMESPACE
data:
  tls.crt: $CRT
  tls.key: $KEY
type: kubernetes.io/tls
EOF
