#!/bin/bash
# exit if any command fails
set -e

verbose=${KR_VERBOSE:-false}
if [ "$verbose" != "false" ]; then
  set -x
  export
fi

if [ "$KR_PRE_HOOK" != "" ]; then
  echo "Running pre hook command: $KR_PRE_HOOK"
  eval "$KR_PRE_HOOK"
fi

build () {
    ./build
}

build () {
    ./install
}

build
install

if [ "$KR_POST_HOOK" != "" ]; then
  echo "Running post hook command: $KR_POST_HOOK"
  eval "$KR_POST_HOOK"
fi
